version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@okta*"
      - dependency-name: "@vx*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
